using Microsoft.EntityFrameworkCore;
using GrindingThunder.Api.Application.Exceptions;
using GrindingThunder.Api.Application.Models;
using GrindingThunder.Api.Domain.Entities;
using GrindingThunder.Api.Domain.Services;
using GrindingThunder.Api.Infrastructure.Persistence;

namespace GrindingThunder.Api.Infrastructure.Services;

/// <summary>
/// Calculates the research points (RP) required to unlock a target vehicle by
/// traversing the explicit prerequisite lines upwards and incorporating
/// player-chosen filler vehicles for rank-gate requirements.
/// No auto-picking of fillers - the frontend supplies explicit FillerTargetIds.
/// </summary>
public class ResearchCalculatorService : IResearchCalculatorService
{
    private readonly ApplicationDbContext _context;

    public ResearchCalculatorService(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<ResearchCalculationResult> CalculateResearchAsync(
        ResearchCalculationRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        if (request.AverageRpPerMatch <= 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(request.AverageRpPerMatch),
                "Average RP per match must be greater than zero.");
        }

        var unlockedSet = (request.UnlockedVehicleIds ?? new List<Guid>())
            .Distinct()
            .ToHashSet();

        var fillerTargetIds = (request.FillerTargetIds ?? new List<Guid>())
            .Distinct()
            .ToHashSet();

        // Load one complete, read-only snapshot. AsSplitQuery avoids a cartesian
        // product while keeping every query generated by this aggregate load
        // constrained by the caller-selected version.
        var version = await _context.ResearchTreeVersions
            .AsNoTracking()
            .AsSplitQuery()
            .Include(v => v.TreeRanks)
            .Include(v => v.Entries)
                .ThenInclude(e => e.Vehicle)
            .Include(v => v.Entries)
                .ThenInclude(e => e.Prerequisites)
            .SingleOrDefaultAsync(
                v => v.Id == request.ResearchTreeVersionId,
                cancellationToken);

        if (version is null)
        {
            throw new ResearchTreeVersionNotFoundException(request.ResearchTreeVersionId);
        }

        var entries = version.Entries.ToList();
        var entryByVehicleId = entries.ToDictionary(e => e.VehicleId);

        if (!entryByVehicleId.TryGetValue(request.TargetVehicleId, out var targetEntry))
        {
            throw new ResearchCalculationInputException(
                $"Target vehicle '{request.TargetVehicleId}' is not present in research tree version " +
                $"'{request.ResearchTreeVersionId}'.");
        }

        var invalidOwnedIds = unlockedSet
            .Where(id => !entryByVehicleId.ContainsKey(id))
            .OrderBy(id => id)
            .ToList();
        if (invalidOwnedIds.Count > 0)
        {
            throw new ResearchCalculationInputException(
                $"Unlocked vehicle IDs are not present in research tree version " +
                $"'{request.ResearchTreeVersionId}': {string.Join(", ", invalidOwnedIds)}.");
        }

        var invalidFillerIds = fillerTargetIds
            .Where(id => !entryByVehicleId.ContainsKey(id))
            .OrderBy(id => id)
            .ToList();
        if (invalidFillerIds.Count > 0)
        {
            throw new ResearchCalculationInputException(
                $"Filler target IDs are not present in research tree version " +
                $"'{request.ResearchTreeVersionId}': {string.Join(", ", invalidFillerIds)}.");
        }

        var ranks = version.TreeRanks.ToList();
        var ranksById = ranks.ToDictionary(rank => rank.Id);
        var entryWithInvalidRank = entries.FirstOrDefault(e => !ranksById.ContainsKey(e.TreeRankId));
        if (entryWithInvalidRank is not null)
        {
            throw new InvalidOperationException(
                $"Vehicle tree entry '{entryWithInvalidRank.Id}' references a rank outside research tree version " +
                $"'{request.ResearchTreeVersionId}'.");
        }

        var vehicles = entries.Select(e => e.Vehicle).ToList();
        var vehicleMap = vehicles.ToDictionary(v => v.Id);
        var vehiclesByRank = entries.GroupBy(e => e.TreeRankId).ToDictionary(g => g.Key, g => g.Select(e => e.Vehicle).ToList());

        // VehicleId -> list of prerequisite vehicle ids (dependency direction points up the tree).
        // Edges are entry-based; translated to vehicle ids via the version's entry map.
        var entryIdToVehicleId = entries.ToDictionary(e => e.Id, e => e.VehicleId);
        var prereqMap = entries
            .SelectMany(e => e.Prerequisites)
            .GroupBy(vp => entryIdToVehicleId[vp.VehicleTreeEntryId])
            .ToDictionary(
                g => g.Key,
                g => g.Select(vp => entryIdToVehicleId[vp.PrerequisiteVehicleTreeEntryId]).ToList());

        // ------------------------------------------------------------------
        // Step 1: Direct line traversal (upward graph search).
        //
        // Starting from the target vehicle, recursively collect every mandatory
        // parent defined by the explicit prerequisite edges. A branch stops as
        // soon as a vehicle has no prerequisites (e.g. a broken column line at
        // Rank IV). Vehicles already present in UnlockedVehicleIds are excluded
        // from the required set.
        // ------------------------------------------------------------------
        var required = new List<Vehicle>();
        var requiredIds = new HashSet<Guid>();
        var visited = new HashSet<Guid>();

        void CollectLine(Guid vehicleId)
        {
            // Unknown vehicle (outside the nation graph) or already traversed.
            if (!vehicleMap.TryGetValue(vehicleId, out var vehicle) || !visited.Add(vehicleId))
            {
                return;
            }

            if (unlockedSet.Contains(vehicleId)) return;

            if (!unlockedSet.Contains(vehicleId))
            {
                requiredIds.Add(vehicleId);
                required.Add(vehicle);
            }

            // No prerequisites -> the line is broken and traversal stops here.
            if (prereqMap.TryGetValue(vehicleId, out var prereqIds))
            {
                foreach (var prereqId in prereqIds)
                {
                    CollectLine(prereqId);
                }
            }
        }

        CollectLine(targetEntry.VehicleId);

        // ------------------------------------------------------------------
        // Step 1b: Collect explicit filler targets and their line prerequisites.
        //
        // Each player-chosen filler vehicle is added along with its full
        // prerequisite chain. Filler prereqs that overlap with the mandatory
        // line (requiredIds) are kept as mandatory (not double-counted).
        // ------------------------------------------------------------------
        var fillerIds = new HashSet<Guid>();
        var fillerVisited = new HashSet<Guid>();
        var fillerVehicles = new List<Vehicle>();

        void CollectFillerLine(Guid vehicleId)
        {
            if (!vehicleMap.TryGetValue(vehicleId, out var vehicle)
                || !fillerVisited.Add(vehicleId))
                return;

            // Already unlocked - skip.
            if (unlockedSet.Contains(vehicleId))
                return;

            // Already part of the mandatory line - no need to also track as filler.
            if (requiredIds.Contains(vehicleId))
            {
                // Still recurse into prerequisites in case they're not in the line.
                if (prereqMap.TryGetValue(vehicleId, out var prereqIds))
                {
                    foreach (var prereqId in prereqIds)
                    {
                        CollectFillerLine(prereqId);
                    }
                }
                return;
            }

            fillerIds.Add(vehicleId);
            fillerVehicles.Add(vehicle);

            // Recurse into prerequisites.
            if (prereqMap.TryGetValue(vehicleId, out var fillerPrereqIds))
            {
                foreach (var prereqId in fillerPrereqIds)
                {
                    CollectFillerLine(prereqId);
                }
            }
        }

        foreach (var fillerId in fillerTargetIds)
        {
            CollectFillerLine(fillerId);
        }

        // ------------------------------------------------------------------
        // Step 2: Rank gate verification (Rank I up to TargetRank - 1).
        //
        // Evaluate each rank sequentially. Count unique vehicles that are
        // either already unlocked, part of the mandatory line, or part of the
        // explicit filler set. If a rank's quota is not met, STOP - return
        // the accumulated results with a RankDeficit for that rank.
        // Do NOT auto-pick fillers.
        // ------------------------------------------------------------------
        var targetRankNumber = ranksById[targetEntry.TreeRankId].RankNumber;
        var rankDeficits = new List<RankDeficitDto>();

        foreach (var rank in ranks
            .Where(r => r.RankNumber < targetRankNumber)
            .OrderBy(r => r.RankNumber))
        {
            var threshold = rank.RequiredVehiclesUnlocked;
            if (threshold <= 0)
            {
                continue;
            }

            var rankVehicles = vehiclesByRank.TryGetValue(rank.Id, out var rv) ? rv : new List<Vehicle>();

            var count = rankVehicles.Count(v =>
                unlockedSet.Contains(v.Id)
                || requiredIds.Contains(v.Id)
                || fillerIds.Contains(v.Id));

            var shortfall = threshold - count;
            if (shortfall > 0)
            {
                // Rank gate not satisfied - report deficit and stop.
                rankDeficits.Add(new RankDeficitDto(
                    rank.RankNumber,
                    shortfall,
                    threshold));

                // Stop evaluating further ranks - the player must resolve
                // this deficit before higher ranks can be calculated.
                break;
            }
        }

        // ------------------------------------------------------------------
        // Step 3: Total RP = mandatory line vehicles + explicit fillers.
        // ------------------------------------------------------------------
        var requiredVehicleSummaries = new List<VehicleRpSummary>(required.Count + fillerVehicles.Count);
        requiredVehicleSummaries.AddRange(required.Select(v =>
            new VehicleRpSummary(v.Id, v.Name, entryByVehicleId[v.Id].RpCost, false)));
        requiredVehicleSummaries.AddRange(fillerVehicles.Select(v =>
            new VehicleRpSummary(v.Id, v.Name, entryByVehicleId[v.Id].RpCost, true)));

        var totalRp = requiredVehicleSummaries.Sum(v => v.RpRemaining);
        var estimatedMatches = (int)Math.Ceiling((double)totalRp / request.AverageRpPerMatch);

        return new ResearchCalculationResult(
            targetEntry.VehicleId,
            totalRp,
            estimatedMatches,
            requiredVehicleSummaries,
            rankDeficits);
    }
}
