// <auto-generated />
using System;
using GrindingThunder.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrindingThunder.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261004054609_IntroduceVehicleTreeEntry")]
    partial class IntroduceVehicleTreeEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.GameUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("GameUpdates");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Nation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RankNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredVehiclesUnlocked")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResearchTreeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTreeId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.ResearchTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("NationId", "VehicleTypeId")
                        .IsUnique();

                    b.ToTable("ResearchTrees");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.ResearchTreeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameUpdateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTreeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameUpdateId");

                    b.HasIndex("ResearchTreeId", "GameUpdateId")
                        .IsUnique();

                    b.ToTable("ResearchTreeVersions");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FolderParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFolderParent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TreeColumn")
                        .HasColumnType("integer");

                    b.Property<int>("TreeRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FolderParentId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehiclePrerequisite", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrerequisiteVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("VehicleId", "PrerequisiteVehicleId");

                    b.HasIndex("PrerequisiteVehicleId");

                    b.ToTable("VehiclePrerequisites");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehicleTreeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTreeVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RpCost")
                        .HasColumnType("integer");

                    b.Property<int>("SlCost")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ResearchTreeVersionId", "VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleTreeEntries");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Rank", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.ResearchTree", "ResearchTree")
                        .WithMany("Ranks")
                        .HasForeignKey("ResearchTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchTree");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.ResearchTree", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Nation", "Nation")
                        .WithMany("ResearchTrees")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrindingThunder.Api.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("ResearchTrees")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.ResearchTreeVersion", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.GameUpdate", "GameUpdate")
                        .WithMany("ResearchTreeVersions")
                        .HasForeignKey("GameUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrindingThunder.Api.Domain.Entities.ResearchTree", "ResearchTree")
                        .WithMany("Versions")
                        .HasForeignKey("ResearchTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUpdate");

                    b.Navigation("ResearchTree");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "FolderParent")
                        .WithMany("FolderChildren")
                        .HasForeignKey("FolderParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FolderParent");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehiclePrerequisite", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "PrerequisiteVehicle")
                        .WithMany("RequiredFor")
                        .HasForeignKey("PrerequisiteVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Prerequisites")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrerequisiteVehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehicleTreeEntry", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Rank", "Rank")
                        .WithMany("TreeEntries")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrindingThunder.Api.Domain.Entities.ResearchTreeVersion", "ResearchTreeVersion")
                        .WithMany("Entries")
                        .HasForeignKey("ResearchTreeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("TreeEntries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("ResearchTreeVersion");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.GameUpdate", b =>
                {
                    b.Navigation("ResearchTreeVersions");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Nation", b =>
                {
                    b.Navigation("ResearchTrees");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Rank", b =>
                {
                    b.Navigation("TreeEntries");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.ResearchTree", b =>
                {
                    b.Navigation("Ranks");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.ResearchTreeVersion", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("FolderChildren");

                    b.Navigation("Prerequisites");

                    b.Navigation("RequiredFor");

                    b.Navigation("TreeEntries");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehicleType", b =>
                {
                    b.Navigation("ResearchTrees");
                });
#pragma warning restore 612, 618
        }
    }
}
