// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using GrindingThunder.Api.Infrastructure.Persistence;

#nullable disable

namespace GrindingThunder.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919073426_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Nation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RankNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredVehiclesUnlocked")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FolderParentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFolderParent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uuid");

                    b.Property<int>("RpCost")
                        .HasColumnType("integer");

                    b.Property<int>("SlCost")
                        .HasColumnType("integer");

                    b.Property<int>("TreeColumn")
                        .HasColumnType("integer");

                    b.Property<int>("TreeRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FolderParentId");

                    b.HasIndex("RankId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehiclePrerequisite", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrerequisiteVehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("VehicleId", "PrerequisiteVehicleId");

                    b.HasIndex("PrerequisiteVehicleId");

                    b.ToTable("VehiclePrerequisites");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Rank", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Nation", "Nation")
                        .WithMany("Ranks")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "FolderParent")
                        .WithMany("FolderChildren")
                        .HasForeignKey("FolderParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GrindingThunder.Api.Domain.Entities.Rank", "Rank")
                        .WithMany("Vehicles")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderParent");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.VehiclePrerequisite", b =>
                {
                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "PrerequisiteVehicle")
                        .WithMany("RequiredFor")
                        .HasForeignKey("PrerequisiteVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrindingThunder.Api.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Prerequisites")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrerequisiteVehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Nation", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Rank", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GrindingThunder.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("FolderChildren");

                    b.Navigation("Prerequisites");

                    b.Navigation("RequiredFor");
                });
#pragma warning restore 612, 618
        }
    }
}
